name: Microsoft Azure CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present

      - name: Inserting azure config to ./build
        run: cp -R ./azureConfig/web.config ./build

      - name: Double-check for catalogues
        run: | 
          ls ./build
          tree -I 'node_modules'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./build


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'limarkdl-UCLan-Merch-Shop'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_29E5DCC69AC7470D8F700A00DE71BDDB }}
          package: './'

  upload_to_blob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob
        uses: azure/CLI@v1
        with:
          inlineScript:
            az storage blob upload-batch --account-name limarkdluclanshopstatic --account-key ${{ secrets.AZURE_LIMARKDLUCLANSHOPSTATIC_BLOB_ACCESS_KEY}} --destination public --source ./public/azureLocalesWrapper --type block --overwrite
      - name: Log out
        run: az logout